-- MySQL import target for raw FMCSA CSV files.
-- Raw tables are created by scripts/import_fmcsa_to_mysql.py using the source headers as TEXT columns.
-- Expected raw tables:
--   raw_company_census
--   raw_vehicle_inspection
--   raw_crash
--
-- Recommended MySQL database:
--   feright_risk_analysis
--
-- Initial analysis model:
--   raw_* tables            = direct CSV landing tables
--   stg_* views             = typed, trimmed, normalized analysis views
--   agg_* tables/views      = carrier-level rollups
--   carrier_risk_summary    = final carrier-level mart

